m = int(input('Qual é a distância em metros? '))
print(f'{m} metros equivalem à {m*100} centímetros, ou {m*1000} mílimetros')
print(f'DM = {m*10}')
print(f'DAM = {m/10}')
print(f'HM = {m/100}')
print(f'KM = {m/1000}')